use ProblemSolvingPlatform;
INSERT INTO Probleme  (title, descr, difficulte) VALUES
('Two Sum',
 'Given an array of integers, return the indices of the two distinct numbers whose sum equals the target. You must solve it in a single pass using a hash map for efficiency.',
 'Easy'),
('Valid Parentheses',
 'Given a string containing characters ( ), { }, [ ], determine if the sequence is valid by ensuring every opening bracket is properly closed in the correct order using a stack.',
 'Easy'),
('Reverse Linked List',
 'Reverse a singly linked list by reassigning pointers iteratively or recursively. Return the head of the new reversed list without creating additional lists.',
 'Easy'),
('Binary Search',
 'Given a sorted array, efficiently locate the position of a target value using the binary search algorithm with O(log n) time complexity. Return -1 if not found.',
 'Easy'),
('Flood Fill',
 'You are given a 2D image and a starting pixel. Replace the region of connected pixels with a new color using DFS or BFS. Only adjacent pixels with the same value are updated.',
 'Medium'),
('Group Anagrams',
 'Given a list of strings, group together all words that are anagrams by sorting each word or using frequency maps. Return a list of grouped anagram lists.',
 'Medium'),
('Maximum Subarray',
 'Find the contiguous subarray within an array of integers that has the largest sum. Use Kadane''s algorithm to achieve optimal linear time performance.',
 'Medium'),
('Rotate Image',
 'Given an n x n matrix, rotate it 90 degrees clockwise in place by performing a transpose followed by a horizontal reverse. No extra matrix should be used.',
 'Medium'),
('Word Search',
 'Given a 2D board and a word, determine if the word exists by exploring adjacent cells horizontally or vertically without reusing the same cell more than once.',
 'Hard'),
('Longest Valid Parentheses',
 'Given a string of parentheses, compute the length of the longest well-formed substring using dynamic programming or a stack-based approach to track valid segments.',
 'Hard');
